### PR TITLE
Implicitly set HDR color space for RGBA16_FLOAT swap chains

### PR DESCRIPTION
**Pull request by doitsujin**
See #3910.

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
We should test how this interacts with ResizeBuffers

**Comment by doitsujin** [comment]
Oh right, that does allow changing the format on the fly for some stupid reason. Great design, thanks Microsoft.

**Comment by PeterTh** [comment]
FWIW, we do exactly that (when someone toggles HDR in-game).

**Comment by doitsujin** [comment]
Did some testing on Windows, looks like RGBA16 **only** exposes scRGB support (even on SDR systems), and any explicitly set color space persists even through incompatible format changes if we change back to that format (e.g. when enabling HDR10 on RGB10A2).

It seems to be rather unreliable though, at least on my AMD setup, I've seen it break completely a couple of times to the point where it's just hard-stuck in SDR mode, or use the wrong color space for exactly one frame before figuring out the correct one.

Either way, updated PR to hopefully behave as expected.

**Pull request merged**
