### PR TITLE
[dxvk] Add DXVK_DISABLE_EXTENSIONS variable 

### PR DESCRIPTION
**Pull request by Samsuper12**
Added variable for disabling Vulkan extensions at runtime.
That's needed for debugging purposes.
Similar to `VKD3D_DISABLE_EXTENSIONS` in Vkd3d.

### CODE REVIEW

**Comment by K0bin** [comment]
Which extensions are you disabling?

**Comment by Samsuper12** [comment]
> Which extensions are you disabling?

Any instance (except VK_KHR_surface/etc) or device extension. In some cases, I want to disable some extensions for debugging Mesa drivers. That feature helps me debug vkd3d-proton and I miss it in DXVK.

**Comment by doitsujin** [comment]
Wouldn't it make more sense to do this as a Vulkan layer?

I'm still rather curious which features we are talking about exactly, since DXVK already provides a way to disable e.g. graphics pipeline libraries.

**Comment by pchome** [comment]
I'm not sure but there was DevSim and now [VK_LAYER_KHRONOS_profiles](https://vulkan.lunarg.com/doc/view/latest/linux/profiles_layer.html)

**Comment by Samsuper12** [comment]
> Unlike vkd3d-proton we're using Vulkan 1.3 core features whenever possible, which adds up to like over 20 extensions at this point which wouldn't be caught by this.

Yep, I wanted to ask about this. Can I also create a variable (or Vulkan layer) for disabling that features?

> since DXVK already provides a way to disable e.g. graphics pipeline libraries.

In some cases driver doesn't support graphics pipeline libraries with the message `info:  DXVK: Graphics pipeline libraries not supported`.  (the trace in the issue reproduces that message on Intel GPUs: https://gitlab.freedesktop.org/mesa/mesa/-/issues/6924)

**Comment by K0bin** [comment]
> In some cases driver doesn't support graphics pipeline libraries with the message info: DXVK: Graphics pipeline libraries not supported. (the trace in the issue reproduces that message on Intel GPUs:

That's not a problem. It'll just use regular pipelines like every earlier version of DXVK.

**Comment by Samsuper12** [comment]
Hmmm, now I think that PR is a mistake. Sorry for the wasted time. Can I close the PR?

But, can anyone give me a task to implement something in DXVK? Something not very important. I want to help with the project, but finding an "entry point" is very hard for me, as you are seeing. I see the Issues page, but I am very tired of working on Mesa without creating something new.

**Comment by ViNi-Arco** [comment]
> But, can anyone give me a task to implement something in DXVK? Something not very important. I want to help with the project, but finding an "entry point" is very hard for me, as you are seeing.

hello dear, something to implement, could you look at my request for Clamp lod bias #2779, maybe that's the starting point you want?

**Pull request closed without merging**
