### PR TITLE
setup_dxvk.sh: don't install 64bit builds to syswow64

### PR DESCRIPTION
**Pull request by aviau**

### CODE REVIEW

**Comment by pchome** [comment]
@doitsujin 
"Fish" vs "fishing"

Simply drop this goddamn script, this will save your from next dozen issues and PR's.

**Comment by aviau** [comment]
I was wrong. Using wine64 winepath and wine winepath is perfectly fine.

**Comment by pchome** [comment]
What stops you from using your own script? Which will perfectly fit all Debian requirements?
Ain't you using patches for some packages?

**Comment by aviau** [comment]
Sure, but minimal diffs are always better.

**Comment by pchome** [comment]
It's helper script to manually build DXVK. If you going to package and support DXVK build in your distribution -- simply add your own helper script. It can't cower all distributions needs on master branch.

**Comment by aviau** [comment]
There was nothing distro-specific in that PR, it was just unneeded.

**Pull request closed without merging**
