### PR TITLE
Refactor shader creation

### PR DESCRIPTION
**Pull request by doitsujin**
Long overdue cleanup of some of the DxvkShader mess. May need some testing.

### CODE REVIEW

**Comment by X33R00** [comment]
Hello Doitsujin thanks for creating this cool software, im one one of the contributors from the dxvk-cache project and we are wondering if this comit will cause shader incompabilities with the current shader cache format or just add new entries.

Mvh/With regards Gruvvv

**Comment by X33R00** [comment]
Screenshot_20220417_120831
The stuttering is gone from Battlefield Bad Company 2 and i also got a nice fps bost from this pull request

**Comment by X33R00** [comment]
Screenshot_20220417_151537
MW4 Remastered gets a nice performance boost after the cache is processed, i havent found any issues yet

**Comment by X33R00** [comment]
Screenshot_20220417_154345
Screenshot_20220417_154205
On the mission where you extract Nikolai dxvk will struggle alot and there will be graphical glitches that i havent been able to screenshot

**Review by Joshua-Ashton — APPROVED** [review]

**Comment by doitsujin** [comment]
> Hello Doitsujin thanks for creating this cool software, im one one of the contributors from the dxvk-cache project and we are wondering if this comit will cause shader incompabilities with the current shader cache format or just add new entries to the curernt cache, please tell me if im unclear.

It doesn't do anything to the cache. It also doesn't affect performance in any way whatsoever.

**Pull request merged**
