### PR TITLE
Implement D3D11DXGIDevice::EnqueueSetEvent

### PR DESCRIPTION
**Pull request by BunniKaitlyn**
Not sure if this is entirely accurate, but works fine in my limited testing. Please let me know if this is correct or if there is any changes I should make.

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Can you let us know what you are testing with if possible? What is using/needs this?

**Comment by Joshua-Ashton** [comment]
I am guessing the Oculus runtime in Wine + DXVK you mentioned on the other MR.

**Review by Joshua-Ashton — APPROVED** [review]
Looking at https://learn.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgidevice2-enqueuesetevent 

The impl makes sense to me, but seems weird that there are two ways of doing this :frog: sus

**Comment by BunniKaitlyn** [comment]
> I am guessing the Oculus runtime in Wine + DXVK you mentioned on the other MR.

Yeah my bad, all testing was done on the Oculus runtime, which requires both of these PRs. Works fine as seen here: https://twitter.com/BunniKaitlyn/status/1768130826506531034

**Comment by ViNi-Arco** [comment]
> Works fine as seen here: https://twitter.com/BunniKaitlyn/status/1768130826506531034

That's interesting, you could pass env WINEDEBUG=fixme-all to suppress all those fixme and gain a bit of performance..

**Pull request merged**
