### PR TITLE
[dxvk] Add sampler count display to HUD

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
Use 'sampler' in DXVK_HUD env var

### CODE REVIEW

**Comment by doitsujin** [comment]
This isn't particularly useful for D3D10/11 since sampler objects aren't persistent (nor a performance issue). It's probably better to rewrite parts of the HUD to make it more extensible, and then put some API-specific stuff into the respective modules.

**Comment by Joshua-Ashton** [comment]
👍

**Comment by pchome** [comment]
:frog: 
dxvk-conky-poc3

**Comment by mozo78** [comment]
Hello pchome,
What program is the green section of the picture?

**Comment by pchome** [comment]
@mozo78 
Conky [[1]](https://en.wikipedia.org/wiki/Conky_%28software%29), [[2]](https://www.deviantart.com/popular-all-time/?section=&global=1&q=Conky&offset=0)

**Comment by mozo78** [comment]
Ah, I know what Conky is but I didn't recognize it. Shame on me :)
Screenshot_20190607_204659
Thank you :)

**Comment by pchome** [comment]
https://github.com/pchome/dxvk-ipc , in case someone want to look at this mess. Includes Conky config example and patches for both DXVK and D9VK.

**Pull request closed without merging**
