### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by srasteiro**
Edited README.md to include a short note about performance increase on Windows for AMD GPU's and lower end CPU's.

### CODE REVIEW

**Comment by srasteiro** [comment]
New joiners wanting to use it may be confused and think this is only for Linux when that is not the case.

**Comment by Blisto91** [comment]
> New joiners wanting to use it may be confused and think this is only for Linux when that is not the case.

It is only meant to be used for Linux as that is the only use case that this repo only really have official support for.
As the [wiki says](https://github.com/doitsujin/dxvk/wiki/Windows#common-issues) it may in general work on Windows, and it's cool when it does (and sometimes we do assist Windows users in issues), but we don't want to officially encourage it as it is outside our scope.

Both Nvidia and Intel use or will use dxvk in some capacity on Windows, but that is separate projects from what this repository offers.

**Comment by K0bin** [comment]
> New joiners wanting to use it may be confused and think this is only for Linux when that is not the case.

It is only for Linux. It working on Windows is a byproduct and not officially supported.

https://github.com/doitsujin/dxvk/wiki/Windows

**Comment by doitsujin** [comment]
Spelling aside, this isn't even true anymore, AMD's driver outperforms DXVK in most games on RDNA2 onwards.

**Pull request closed without merging**
