### PR TITLE
Always disable exclusive full-screen on Windows

### PR DESCRIPTION
**Pull request by doitsujin**
So far we're always letting the driver decide whatever it wants to, but since Windows doesn't seem to give drivers any sort of low-level access to anything more modern than D3D9-level presentation APIs we just end up in a situation that sucks for everyone anyway, so migth as well disable it and at least have a slim chance of things like alt+tab actually working.

Should also fix #4465 and related issues, I can't be arsed to add hundreds of app profiles for this garbage.

### CODE REVIEW

**Comment by Blisto91** [comment]
Touches issue
https://github.com/doitsujin/dxvk/issues/2640
https://github.com/doitsujin/dxvk/issues/3963
And maybe or maybe not
https://github.com/doitsujin/dxvk/issues/3819
https://github.com/doitsujin/dxvk/issues/1694
https://github.com/doitsujin/dxvk/issues/4147

**Comment by qinlili23333** [comment]
Approve for short term until we can find some better way to handle FSE. 

Actually these days I'm also considering about detecting WS_SYSMENU flag and only enable DSE for those without this flag. I tested variety of games including normal AAA titles and AVG with different engines. I found that those games cannot work well under FSE all have WS_SYSMENU flag even under fullscreen while most AAA titles like UE3 titles usually remove this flag when entering fullscreen. I'm not sure whether we can detect this flag and do sth better, so I approve we should disable FSE globally until we have developed sth better.

**Comment by doitsujin** [comment]
I want to avoid fucking around with window flags / messages at all costs. I also just don't want to deal with annoying Windows quirks that simply do not exist on other platforms.

**Comment by mirh** [comment]
> Windows doesn't seem to give drivers any sort of low-level access to anything more modern than D3D9-level presentation APIs

I'm not sure I understand the referent. 
Are we talking about modern presentation as in having vulkan use DXGI rather than GDI, or low-level access as in using something like D3DKMTWaitForVerticalBlankEvent rather than old ass (and/or [finnicky](https://github.com/SpecialKO/SpecialK/commit/a1f63d3aa6dfcdb0b1fdf97bc2a7421057a16350)) WaitForVBlank & friends?

> Sadly it seems WS_SYSMENU is still not a good idea.

How about that *and* if it has any children? 
(notably enough WS_CHILD and WS_POPUP are incompatible, the later being the old way I knew you could set non-d3d FSE)

**Comment by qinlili23333** [comment]
> Are we talking about modern presentation as in having vulkan use DXGI rather than GDI
Sadly, many applications rely on GDI compatibility, and some of them need DXGI in the same time. For a wrapper which prefer compatibility instead of performance, it's unacceptable to use these solutions which may break compatibility. SpecialK is more performance preferred and focus on game only, that's why it can use many aggressive optimization which may break compatibility. (e.g. You can even use DXVK for libcef based applications, but you cannot use SpeciakK)

**Pull request merged**
