### PR TITLE
[build] detect and report DXVK version

### PR DESCRIPTION
**Pull request by pchome**
#488
Version reported in log and HUD like `DXVK: 0.61 (56f7ef5)`

### CODE REVIEW

**Comment by pchome** [comment]
> Has this been tested on Windows?

no
> What happens if the command to retrieve the version fails?

`meson.build:9:0: ERROR:  Program or command 'head123' not found or not executable`
or, I suppose, `run_command().stdout()` will return nothing if command exists but prints to `.stderr()`
> I'm really not a fan of those `#ifdefs`, they should all be removed.

they was added for cases when DXVK compiled from sources (.tar.gz) and not possible to detect git version, but they don't work as expected (since there is no corresponding condition checks)
> and I'd prefer to add it as a separate option rather than adding it to the `devinfo` thing.

"Software info block" logic used, not sure it needs separate option, but...

feel free to reject this PR

**Comment by pchome** [comment]
Last commits should check commands and fix general logic of `#ifdefs`. For `.tar.gz` builds will show only `DXVK: 0.61`. On Windows or fail should not show DXVK version (linux only PR).

**Comment by doitsujin** [comment]
Thanks for the update. It's fine if the version display doesn't work on Windows builds, but it shouldn't break them. I'll take a closer look at this tomorrow.

**Comment by GloriousEggroll** [comment]
What if we make it give the DXVK version number by default, and add the git commit number only if it's not null? that way it always has a version number, doesn't require ifdefs, and shouldnt spit out an error because it wouldnt add anything to the version number if it was found to be null

**Comment by doitsujin** [comment]
After reading some documentation, Meson already has a farily convenient way of forwarding git tags and commit hashes with the [vcs-tag](http://mesonbuild.com/Reference-manual.html#vcs_tag) command, so I went with that. In any case, thanks for the effort.

**Pull request closed without merging**
