### PR TITLE
[meta] Add Robin Kertels to LICENSE file

### PR DESCRIPTION
**Pull request by K0bin**
As suggested by Misyl on Discord

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
I'll merge after we merge D3D8, so save Jeff the pain of rebasing for a license change :-)

**Comment by Blisto91** [comment]
Finally 🎉 🐦 🎉

**Comment by Joshua-Ashton** [comment]
can u rebase

**Comment by K0bin** [comment]
done

**Pull request merged**
