### PR TITLE
[d3d9] Implement partial presentation

### LINKED ISSUE #1476: [d3d9] Evenicle - Crash to desktop at startup (wine) / Black screen (proton)
I was a bit hesitant at first to report the issue, the game being a H-game and all, but hey, these games also need some love, don't judge please :)

The issue is the following :

If I try running the game using proton;
- Using version 4.11, the game run properly.
- Using version 5.0.3, the game render as a black screen. I am still able to press the buttons from the main menu and do stuff, I am only unable to see what I am doing.

If I try running the game using the latest wine and DXVK
- I create a new wine prefix and then run setup_dxvk.sh install --symlink
- I cd into the game directory and run "wine Evenicle.exe".
- The game imediately crashes. I get the following backtrace from wine: 
[Evenicle-backtrace.txt](https://github.com/doitsujin/dxvk/files/4253107/Evenicle-backtrace.txt)

If I try running the game using the latest wine without DXVK
- I create a new wine prefix
- I cd into the game directory and run "wine Evenicle.exe".
- The game is working properly without issues

### Software information
Evenicle, steam build
https://store.steampowered.com/app/955560/Evenicle/

### System information
- GPU: Nvidia GTX 970
- Driver: Proprietary, 440.59
- Wine version: 5.2 (staging)
- DXVK version: 1.5.4-55-gfbf76e84+ (Last commit on master).

### Apitrace file(s)
[Evenicle.trace.zip](https://github.com/doitsujin/dxvk/files/4253085/Evenicle.trace.zip)

### Log files
- d3d9.log: [Evenicle_d3d9.log](https://github.com/doitsujin/dxvk/files/4253084/Evenicle_d3d9.log)

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
This implements partial presentation when applications use D3DSWAPEFFECT_COPY in such a way that apps that specify that and don't end up ever partially presenting will not be penalized performance wise (instead a slight penalty is applied by an extra blit to those who do.)

Closes #1476

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
In retrospect, there are still some issues in this PR I need to work out.

**Comment by Joshua-Ashton** [comment]
Fixed some val errors... Need to find out where the random black boxes come from sometimes though.

**Comment by pchome** [comment]
@Joshua-Ashton 
May I ask you why frog-push ?
This thing is very confusing for RSS and mail notification, when e.g. github sends several similar messages in a row. Also it's much harder to review changes.

**Comment by Joshua-Ashton** [comment]
Because that's how you update PRs..?

**Comment by pchome** [comment]
Regular commit into PRed branch, that's how people usually update PRs on github.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/github-flow
> 4. Make changes on your branch as needed. Your pull request will update automatically.

I don't know if something changed by github itself, or it's an tool you using as git frontend, but if you doing force pushes intentionally -- please don't, if possible.

**Comment by Joshua-Ashton** [comment]
Bruh, it's my PR. I don't want superfluous (ie. what could be fixup) commits being merged in -- and we don't squash and merge either.

**Comment by ojeda** [comment]
> Regular commit into PRed branch, that's how people usually update PRs on github.
> https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/github-flow

Well, GitHub got it wrong ;-) In "Git-native" projects, PRs are versioned, sent and reviewed again as a whole, rather than fixes on top of fixes. It would be great if GitHub added proper support for that.

**Comment by doitsujin** [comment]
Github isn't a mailing list.

**Comment by ojeda** [comment]
That has nothing to do with whether GitHub could or not support versioned PRs.

**Comment by pchome** [comment]
@Joshua-Ashton 
> Bruh, it's my PR.

Sure, I not teaching you, but also I didn't mean this particular PR but your force-push method in general. It was pain to update local D9VK git repos, also every your commit into master regenerated whole RSS list, but ok, it was your repo.

But, recently I noticed other people started doing the same, see your and DadSchoorse PRs into Proton's wine repo. So, this one is the PR where I noticed force-push again and where I reported you about some issues with this method, and where I kindly ask you to follow the service rules and to use force-push where it really needed.

I understand if you don't care, but I also hope this force-push method will not spread widely.

P.S. Btw, you also broke Wine's upstream mailing list with your recent PR there ;)

**Comment by Joshua-Ashton** [comment]
Dude, this is literally how *everyone* updates PRs on GitHub.

> I kindly ask you to follow the service rules and to use force-push where it really needed.

There are no such "rules".

> I understand if you don't care

You would be correct in that.
Let's stop speaking about it.

**Pull request closed without merging**
