### PR TITLE
Add config for C&C Generals ZH (solve crashing + performance increase )

### PR DESCRIPTION
**Pull request by anoosi**
Solved the problem of the game crashing when it starts loading saved missions or skirmish, especially for Mods
+ Huge performance increase.
+ Solve Alt tab crashing.

### CODE REVIEW

**Comment by WinterSnowfall** [comment]
For anyone who might not be aware, this is actually a d3d8 game.

@anoosi `"d3d9.textureMemory", "2048"` seems a bit excessive to say the least... and so does the value for `d3d9.maxAvailableMemory`. How did you come up with these numbers?

**Comment by anoosi** [comment]
> For anyone who might not be aware, this is actually a d3d8 game.
thanks for mention that.
+using d3d8to9
> 
> @anoosi `"d3d9.textureMemory", "2048"` seems a bit excessive to say the least... and so does the value for `d3d9.maxAvailableMemory`. How did you come up with these numbers?
> 
> P.S.: You can use `"d3d9.textureMemory", "0"` to disable the limit entirely, if that's what you're after.
If you play with ai like map 8 players, there will be a large amount of texture that must be loaded, especially if it is a replay file or a saved skirmish, missions,
some mod, contains high resolution textures and the size of files much bigger , also some mods contains high poly  3d objects,
i tested so many times d3d9.maxAvailableMemory = 4GB sometimes crashing if you play mods like CWC with a long session playing.

**Comment by anoosi** [comment]
> For anyone who might not be aware, this is actually a d3d8 game.
> 
> @anoosi `"d3d9.textureMemory", "2048"` seems a bit excessive to say the least... and so does the value for `d3d9.maxAvailableMemory`. How did you come up with these numbers?
> 
> P.S.: You can use `"d3d9.textureMemory", "0"` to disable the limit entirely, if that's what you're after.


If you play with ai like map 8 players, there will be a large amount of texture that must be loaded, especially if it is a replay file or a saved skirmish, missions,
some mod, contains high resolution textures and the size of files much bigger , also some mods contains high poly  3d objects,
i tested so many times d3d9.maxAvailableMemory = 4GB sometimes crashing if you play mods like CWC with a long session playing.

**Comment by Blisto91** [comment]
Which of these variables are you saying help with crashing?
`d3d9.maxAvailableMemory` caps at 4GB which is already default so the value you set doesn't do anything (the value is in megabytes).
If not raising `d3d9.textureMemory` makes the game crash then I'd like you to make an issue.

I assume you are using d8vk or d3d8to9 with it for it to work with dxvk?

**Comment by anoosi** [comment]
> Which of these variables are you saying help with crashing? `d3d9.maxAvailableMemory` caps at 4GB which is already default so the value you set doesn't do anything (the value is in megabytes). If not raising `d3d9.textureMemory` makes the game crash then I'd like you to make an issue.
> 
> I assume you are using d8vk or d3d8to9 with it for it to work with dxvk?

maybe the problem with d3d9.textureMemory only
d8vk and d3d8to9 same problem.

**Comment by WinterSnowfall** [comment]
> `d3d9.maxAvailableMemory` caps at 4GB which is already default so the value 

True, but note it still needs a `"d3d9.memoryTrackTest", "True"` to actually enforce that limit IIRC.

I only have the base game (or the addon, rather) and haven't noticed any problems even on the largest maps, however I don't use any mods, so can't comment on that front.

**Comment by anoosi** [comment]
> > `d3d9.maxAvailableMemory` caps at 4GB which is already default so the value
> 
> True, but note it still needs a `"d3d9.memoryTrackTest", "True"` to actually enforce that limit IIRC.
> 
> I only have the base game (or the addon, rather) and haven't noticed any problems even on the largest maps, however I don't use any mods, so can't comment on that front.

if you start the game like skirmish there is no issue,  but, if you load a replay or saved skirmish or mission it will get crash!
i faced this in the game without mods in sometimes, but it's happen always with mods that contains 3d objects with high resolution textures.
+ i update the configuration (Remove d3d9.maxAvailableMemory)

**Comment by WinterSnowfall** [comment]
> if you start the game like skirmish there is no issue, but, if you load a replay or saved skirmish or mission it will get crash! i faced this in the game without mods in sometimes, but it's happen always with mods that contains 3d objects with high resolution textures.

FWIW, I've tried my best to make the vanilla game (& addon) crash with loading games/replays from large maps, but it never did in my case. Alt+tabbing seems to cause a crash on refocus, but none of the suggesting config options fix it (not that I expected them to).

I also get no performance benefit with any of these options. Again, I've only tested things unmodded, but it would be rather strange if the game's engine would behave differently when modded. The only thing I can think of is that the game's hard limited to 31.2 fps by default, so if any mods change that perhaps some engine bottlenecks become more apparent.

If you mention the game's crashing during long play sessions, are you sure you're using a LAA executable (or Proton, which enables LAA globally)? Issues solved by tweaking d3d9.maxAvailableMemory / d3d9.memoryTrackTest don't usually manifest in time, but are rather more abrupt.

**Pull request closed without merging**
