### PR TITLE
[build] reduce the number of d3dcompiler versions

### PR DESCRIPTION
**Pull request by Mixaill**
use only d3dcompiler_43 for DXVK builds

### CODE REVIEW

**Comment by doitsujin** [comment]
Is it **really** necessary to use _47 on MSVC? not that i have too many objections, but the two GUIDs are kind of ugly.

**Comment by Mixaill** [comment]
>Is it really necessary to use _47 on MSVC? not that i have too many objections, but the two GUIDs are kind of ugly.

Other option is to redistribute `.lib` file from `d3dcompiler_43` with DXVK.

**Comment by Mixaill** [comment]
@doitsujin added `.lib` files to DXVK, it should be much nicer.

**Comment by doitsujin** [comment]
Hmm. I would prefer this solution, but wouldn't that violate licenses?

**Comment by Mixaill** [comment]
@doitsujin replaced libs files with generated myself via `lib` tool:
```
lib /DEF:lib/libd3dcompiler_43.def /OUT:lib/d3dcompiler_43.lib /MACHINE:X64
lib /DEF:lib32/libd3dcompiler_43.def /OUT:lib32/d3dcompiler_43.lib /MACHINE:X86
```

**Comment by doitsujin** [comment]
Great, thanks for getting this to work.

**Pull request merged**
