### PR TITLE
[util] Disable DC Single Use Mode for Cardfight!! Vanguard Dear Days

### PR DESCRIPTION
**Pull request by K0bin**
https://github.com/ValveSoftware/Proton/issues/6318

Props to @Blisto91 for noticing it.

### CODE REVIEW

**Comment by Blisto91** [comment]
Proton experimental bleeding edge should have it

**Comment by My1** [comment]
is that another option that I dont know yet or is "proton experimental" already it?

**Comment by K0bin** [comment]
Just wait for it to ship in Proton Experimental.

**Comment by My1** [comment]
okay thanks. also in the release the exe name doesnt seem to have changed so the change should also be good for that.

(kinda hilarious to go by exe names tho)

**Comment by My1** [comment]
I went on a search, as I wanted to try it to also report on it, and can confirm it works, the display issue is gone

**Comment by Blisto91** [comment]
Note that bleeding edge pulls latest changes automatically and so can be less stable than regular experimental. So i don't recommend it for regular playing. :slightly_smiling_face:

**Comment by My1** [comment]
well experimental is, well, experimental, likely not a default for most games

**Comment by K0bin** [comment]
Bleeding Edge is an opt in beta for Proton Experimental and basically pulls in all committed changes automatically.

It's not recommended for regular users.

**Pull request merged**
