### PR TITLE
[dxvk] Disable graphics pipeline libraries on 32-bit builds

### PR DESCRIPTION
**Pull request by doitsujin**
Can't say I'm overly happy with this but unless we find a way to make all D3D9 games work reliably with the feature enabled we don't really have much of a choice.

### CODE REVIEW

**Comment by K0bin** [comment]
Wouldn't it be a better idea to just disable it for RE6? Everything else I tested has a very low number of shaders anyway (<2000).

**Comment by Joshua-Ashton** [comment]
We should reach out to NV first and see if there are easy address space wins that make this more viable.

**Comment by doitsujin** [comment]
@K0bin I'd argue that those games with a low shader count also don't really need graphics_pipeline_library to be reasonably enjoyable.

**Comment by K0bin** [comment]
Fair enough.

**Review by K0bin — APPROVED** [review]

**Pull request closed without merging**
