### PR TITLE
Use bsf instead of tzcnt where mask != 0

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
For when we know we aren't going to put in a mask of 0, we can use this and get better codegen.

There actually isn't anywhere we actually care about mask == 0 as we already check for that case to end the loop ourselves.

### CODE REVIEW

**Comment by doitsujin** [comment]
This kind of looks like it's changing something for the sake of changing something, I don't really like functions with undefined behaviour in some cases in the first place and saving two instructions in these places won't really affect performance.

**Comment by Joshua-Ashton** [comment]
Then can we change tzcnt to use the builtin with a check instead of inline asm? That gets optimized away on GCC.

**Comment by doitsujin** [comment]
Can't we just implement a proper iterator rather than doing some weird hacks? Like https://gcc.godbolt.org/z/v7M6oY4M6

**Comment by DadSchoorse** [comment]
here's a branch that uses @doitsujin's iterator https://github.com/doitsujin/dxvk/compare/master...DadSchoorse:bititer

**Pull request closed without merging**
