### PR TITLE
[dxso] Handle half texel offset for FETCH4

### PR DESCRIPTION
**Pull request by Joshua-Ashton**

### CODE REVIEW

**Comment by doitsujin** [comment]
I don't like the `const*Replicant` helpers. `constuReplicant` is unused, `constfReplicant` is used literally *once*, the name sounds stupid, and we're probably not going to be using those *anywhere* else.

**Comment by Joshua-Ashton** [comment]
> constfReplicant is used literally once

????

image

image

**Comment by doitsujin** [comment]
sorry, i meant consti*.

Ah, well, whatever, if we have `f` anyway... just saying I don't like it very much.

**Comment by Joshua-Ashton** [comment]
May as well complete the family :frog:

**Pull request merged**
