### PR TITLE
Constant Buffer Bounds check option

### PR DESCRIPTION
**Pull request by K0bin**
This brings back 621aed5fdbaf92764944be7b3a27cbb3df63ba94 but disables it for everything other than Dark Souls Remastered.

### CODE REVIEW

**Comment by doitsujin** [comment]
This conflicts with e5a06d3f4a103a54cd4eb51970fedee405d1d698, so a new implementation would be necessary.

And I can't really say I'm a fan of messing around with basic shader code like this right now.

**Comment by GloriousEggroll** [comment]
This also fixes the flicker in Grim Dawn on some nvidia cards

**Comment by GloriousEggroll** [comment]
I think this should be fixed now as of commit: https://github.com/doitsujin/dxvk/commit/8f580efa25054ea46994c63fce6d2b50ebcbde0c

ZeroFault verified on discord that it does

**Comment by Tk-Glitch** [comment]
And I verified that it doesn't :smile:

**Comment by GloriousEggroll** [comment]
> And I verified that it doesn't smile

yep deleted my comment. /facepalm

**Comment by lieff** [comment]
Hmm, may be it's last hotfix2 patch? I verify it again later.

**Comment by GloriousEggroll** [comment]
latest upstream with this patch causes game to crash at crate logo on AMD, here's a patch so that it only checks for the option on dxbc if the user is on nvidia
`
diff --git a/src/dxbc/dxbc_options.cpp b/src/dxbc/dxbc_options.cpp
index cce1391..5bb08aa 100644
--- a/src/dxbc/dxbc_options.cpp
+++ b/src/dxbc/dxbc_options.cpp
@@ -27,10 +27,12 @@ namespace dxvk {
       = (devInfo.core.properties.limits.minStorageBufferOffsetAlignment <= sizeof(uint32_t));
     useSdivForBufferIndex
       = adapter->matchesDriver(DxvkGpuVendor::Nvidia, VK_DRIVER_ID_NVIDIA_PROPRIETARY_KHR, 0, 0);
-    
+
     strictDivision          = options.strictDivision;
     zeroInitWorkgroupMemory = options.zeroInitWorkgroupMemory;
-    
+    if (adapter->matchesDriver(DxvkGpuVendor::Nvidia, VK_DRIVER_ID_NVIDIA_PROPRIETARY_KHR, 0, 0))
+      checkConstantBufferBounds = options.checkConstantBufferBounds;
+
     // Disable early discard on RADV due to GPU hangs
     // Disable early discard on Nvidia because it may hurt performance
     if (adapter->matchesDriver(DxvkGpuVendor::Amd,    VK_DRIVER_ID_MESA_RADV_KHR,          0, 0)

`

**Comment by K0bin** [comment]
That's weird. I don't see why it would crash.

All the patch does is add index < cbuffer.Size ? cBuffer[index] : vec4(0,0,0,0].

Maybe I messed up the rebase.

**Comment by doitsujin** [comment]
I guess the problem is that you're mixing a vec4 with a smaller vector now. Constant buffer loads don't always load a vec4 anymore.

I promise to revisit this issue before tagging the 1.1 release. :frog:

**Comment by K0bin** [comment]
I'll just close this and leave it to you then.

**Pull request closed without merging**
