### PR TITLE
[util] Set deviceLossOnFocusLoss for Assassin's Creed 2

### LINKED ISSUE #3653: Assassin's Creed 2 alt tab crash
While testing this game on Windows for another issue i noticed that it will crash with dxvk when you alt tab.
Default with dxvk without any configs the game will close down as soon as you alt tab out and it is minimized.

When using `d3d9.deviceLossOnFocusLoss = True` the game will not immediately crash upon a alt tab but it also doesn't work properly as the desktop mouse cursor will appear but the game Window will stay up on top of any other apps. You can force it down by doing a alt tab and then ctrl + alt + del and selecting task manager. When you then try to go back in to the game it will crash.

If  `d3d9.deviceLossOnFocusLoss = True` is combined with `d3d9.enableDialogMode = True` you are able to alt tab out fine and if you don't touch anything else you can also alt tab back in. If you interact with anything while alt tabbed like clicking with the mouse the game will likely crash when you try to go back in. Same if you do it by clicking on the game icon in the taskbar.
So `d3d9.deviceLossOnFocusLoss = True` seems to improve the behavior as the game won't shut down immediately when you get to desktop, but it is still crash prone.

This have all been tested on Windows only so far. Linux testing pending but i was asked to make an issue

### Software information
Assassin's Creed 2 fullscreen

### System information
- GPU: 7900xtx
- Driver: 23.8.2
- Wine version: Windows 11 only so far. ~~Linux test pending~~ See first comment
- DXVK version: Master

### Apitrace file(s)
https://drive.proton.me/urls/QDG5P4RTB4#QDx3b0yg3NsK

Two traces from Windows. One is native game where i alt tab out and in and second is with dxvk with `d3d9.deviceLossOnFocusLoss = True` and  `d3d9.enableDialogMode = True` and it crashing when i try to go back in to the game.

### Log files
[AssassinsCreedIIGame_d3d9.log](https://github.com/doitsujin/dxvk/files/12505974/AssassinsCreedIIGame_d3d9.log)

### PR DESCRIPTION
**Pull request by Blisto91**
Makes it not crash on alt tab when using at least Proton on Linux. Was unable to test regular Wine or Staging as Ubisoft Connect doesn't work there currently.
See [issue description](https://github.com/doitsujin/dxvk/issues/3653) for behavior on Windows.

Closes #3653

### CODE REVIEW

**Review by K0bin — APPROVED** [review]

**Comment by ViNi-Arco** [comment]
I confirm, adding `d3d9.deviceLossOnFocusLoss = True` manually in dxvk.conf fixes the alt+tab in AC2 for me

**Comment by ViNi-Arco** [comment]
> Ubisoft Connect doesn't work there currently.

Disable ESYNC and FSYNC as well, after Ubisoft connect has updated correctly, close it, enable ESYNC/FSYNC and open Ubisoft connect again and have fun..

**Comment by Blisto91** [comment]
Upstream Wine doesn't have Esync or Fsync. It's just a issue that has been worked around in Proton

**Comment by ViNi-Arco** [comment]
> Upstream Wine doesn't have Esync or Fsync

Wine Staging has ESYNC, that I am using..

and you can get FSYNC in Wine using [wine-tkg-git](https://github.com/Frogging-Family/wine-tkg-git)

**Pull request merged**
