### PR TITLE
[util] Don't call GetCurrentThreadId() on every spin

### PR DESCRIPTION
**Pull request by imaami**
Signed-off-by: Juuso Alasuutari <juuso.alasuutari@gmail.com>

### CODE REVIEW

**Comment by imaami** [comment]
Updated to restore compliance with C++11's Lockable requirement should it become an issue in the future. Thanks to Torge for pointing this out on Discord.

**Comment by doitsujin** [comment]
does this lead to any tangible improvements anywhere?

**Comment by imaami** [comment]
> does this lead to any tangible improvements anywhere?

I'd be surprised if it did. On the other hand there's no reason I can think of why `GetCurrentThreadId()` should be called on every loop. @Guy1524 said on Discord that he checked and found out the call doesn't get inlined by MingGW, so there's at least a nano-optimization there.

**Comment by doitsujin** [comment]
Yeah, don't really see the point to be honest other than making the implementation unnecessarily clunky. We're literally just spinning faster, in a way this even the opposite of what we actually want.

**Pull request closed without merging**
