### PR TITLE
Fixes for Spellforce

### LINKED ISSUE #2710: Spellforce platinum edition crash on save
Game crashes when autosaving(with ESC button), quicksaving(F7) and on manual save. Happens both on windows and linux.

With dxvk 1.5.4 the game doesn't crash, but savegame preview is a black square.
Also on linux framerate is very low if i don't constantly move the cursor.

### Software information

Spellforce: Platinum Edition steam

### System information
- GPU: rx5700xt
- Driver: 22.10.01.03 on windows / Mesa 22.0.1 on linux
- Wine version: Proton GE 7-24
- DXVK version: 1.10.1

### Apitrace file(s)
Windows: https://drive.google.com/file/d/1PJis9yE40_K-85_cEfd73kr39xamYXPm/view?usp=sharing

### Log files

- d3d9.log: [SpellForce_d3d9.log](https://github.com/doitsujin/dxvk/files/9078842/SpellForce_d3d9.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #2710

### CODE REVIEW

**Review by doitsujin — APPROVED** [review]

**Comment by gameforkids** [comment]
Guys, I may be disobeying the guidelines for a comment like this but I am a simple man and need help, how do I implement this? Can someone PLEASE help me? I just want to play the game with my wife, but it always crashes upon saving, just like it is here, so I'd like to try this fix.

I just can't seem to work out how this is supposed to work, please help. My steam friend code for easier communication: 88688293

**Comment by gameforkids** [comment]
> I think Steam already ships the fix.

What do you mean?

**Comment by K0bin** [comment]
I mean that if you start the game from Steam, it should just work because Steam already has the fixed version of DXVK.

**Comment by gameforkids** [comment]
> I mean that if you start the game from Steam, it should just work because Steam already has the fixed version of DXVK.

Then either it's not there for some reason, or the problem lies elsewhere... This is getting more and more interesting. I don't even know what to fix anymore.

**Comment by K0bin** [comment]
Can you join this Discord server: https://discord.gg/eyjKrnJ5

Doing this via Github comments is pretty slow.

**Comment by gameforkids** [comment]
> Can you join this Discord server: https://discord.gg/eyjKrnJ5
> 
> Doing this via Github comments is pretty slow.

I'm in

**Pull request merged**
