### PR TITLE
Add workarounds for RE8

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
This PR adds a global DXGI factory for Resident Evil 8 as it spams `CreateDXGIFactory` calls.

This also caches display modes on DXGI outputs as the game also enumerates them every frame which was causing allocations for us due to the way this was handled previously.

Now the game gets put on a fast path where it just ends up returning the cached data constantly.

### CODE REVIEW

**Comment by doitsujin** [comment]
> This PR adds a global DXGI factory for Resident Evil 8 as it spams CreateDXGIFactory calls.

Does this match Windows behaviour?

**Comment by Joshua-Ashton** [comment]
It does not. The pointers are definitely different on Windows, but the overhead is much lower there.

**Comment by Andon13** [comment]
Actually, there's pretty significant performance overhead from this in Windows too.

Special K shows about 3 ms in API shenanigans every time the engine does this stuff.

My solution involves caching the factory, caching the IDXGIAdapter1 acquired using said factory, and then caching the mode list until the factory's `IsCurrent (...)` method fails. At which point, it's necessary to teardown that factory, cache and all.

**Comment by doitsujin** [comment]
caching DXGI factories seems strictly wrong though so we're not going to do that.

**Comment by Andon13** [comment]
Fair enough.

I'm all but certain the reason for this behavior in the engine is because Capcom doesn't know about `WM_DISPLAYCHANGE` notifications and the correct usage of `IDXGIFactory1::IsCurrent (...)`. They are releasing an re-acquiring a new factory every frame because otherwise Windows returns a stale cached mode list.

Their resolution management code in general is terrible.


As long as DXVK is performant while the engine is going about getting resolutions the wrong way, you shouldn't need to cache factories. On Windows, there's substantial overhead caused by releasing these factories, since `GetDisplayModeList (...)` API overhead is much higher immediately after creating a new factory.

**Comment by Oschowa** [comment]
I'm pretty sure this is fixed in the game with the patch released on August 10th. I've tried with an unpatched build of DXVK's DXGI and get 300 fps with CPU bound settings on the title screen which was a slide-show before without this workaround. Also tagging @aeikum for the workaround in wine's DXGI in proton experimental.

**Pull request closed without merging**
