### PR TITLE
Update CI to latest ubuntu

### PR DESCRIPTION
**Pull request by Snowiiii**

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Why? These things run in Arch/Steam Runtime containers anyway and it isn't broken...

**Comment by Snowiiii** [comment]
> Why? These things run in Arch/Steam Runtime containers anyway and it isn't broken...

Updating GitHub CI from Ubuntu 20.04 to 22.04 is essential for the following reasons:

    Latest Software and Security Updates: Ubuntu 22.04 introduces newer versions of software packages and libraries. By updating, you can leverage the latest features, bug fixes, and security patches, ensuring that your CI environment is up to date and protected against vulnerabilities.

    Improved Performance: Ubuntu 22.04 incorporates performance optimizations that can enhance the speed and efficiency of your CI pipeline. With updated system components and an improved kernel, you can expect faster build and test execution times, resulting in quicker feedback for developers.

    Compatibility and Future-Proofing: As the software landscape evolves, newer tools and frameworks may require updated system dependencies. By upgrading to Ubuntu 22.04, you ensure compatibility with the latest software ecosystem. This future-proofs your CI infrastructure, allowing you to seamlessly adopt newer technologies and libraries as your projects evolve.

    Community Support: As Ubuntu 20.04 reaches its end-of-life (EOL) phase, the community's focus shifts to maintaining and supporting newer releases like Ubuntu 22.04. By upgrading, you can tap into the vibrant community support, accessing resources, tutorials, and fixes specific to the latest version.

    Enhanced Stability: Ubuntu 22.04 undergoes rigorous testing and quality assurance processes, resulting in a more stable and reliable operating system. By upgrading, you can benefit from improved stability, reducing the likelihood of unexpected failures during the CI process.

In conclusion, updating GitHub CI from Ubuntu 20.04 to 22.04 offers the advantages of newer software, improved performance, compatibility, community support, and enhanced stability. By embracing the latest Ubuntu release, you can optimize your CI pipeline and ensure a secure and efficient development environment.

**Comment by doitsujin** [comment]
That's a nice amount of buzzwords right there but none of that really answer the question.

I guess there's no reason *not* to update either but given what Josh said, we don't really rely on this.

**Comment by Snowiiii** [comment]
This is a small and straightforward pull request (PR). It is a simple change that doesn't aim to heavily improve anything in particular.

**Comment by Snowiiii** [comment]
@doitsujin what do you say ?

**Comment by sykhro** [comment]
> > Why? These things run in Arch/Steam Runtime containers anyway and it isn't broken...
> 
> Updating GitHub CI from Ubuntu 20.04 to 22.04 is essential for the following reasons:
> 
> ```
> Latest Software and Security Updates: Ubuntu 22.04 introduces newer versions of software packages and libraries. By updating, you can leverage the latest features, bug fixes, and security patches, ensuring that your CI environment is up to date and protected against vulnerabilities.
> 
> Improved Performance: Ubuntu 22.04 incorporates performance optimizations that can enhance the speed and efficiency of your CI pipeline. With updated system components and an improved kernel, you can expect faster build and test execution times, resulting in quicker feedback for developers.
> 
> Compatibility and Future-Proofing: As the software landscape evolves, newer tools and frameworks may require updated system dependencies. By upgrading to Ubuntu 22.04, you ensure compatibility with the latest software ecosystem. This future-proofs your CI infrastructure, allowing you to seamlessly adopt newer technologies and libraries as your projects evolve.
> 
> Community Support: As Ubuntu 20.04 reaches its end-of-life (EOL) phase, the community's focus shifts to maintaining and supporting newer releases like Ubuntu 22.04. By upgrading, you can tap into the vibrant community support, accessing resources, tutorials, and fixes specific to the latest version.
> 
> Enhanced Stability: Ubuntu 22.04 undergoes rigorous testing and quality assurance processes, resulting in a more stable and reliable operating system. By upgrading, you can benefit from improved stability, reducing the likelihood of unexpected failures during the CI process.
> ```
> 
> In conclusion, updating GitHub CI from Ubuntu 20.04 to 22.04 offers the advantages of newer software, improved performance, compatibility, community support, and enhanced stability. By embracing the latest Ubuntu release, you can optimize your CI pipeline and ensure a secure and efficient development environment.

hello chatgpt!

**Pull request closed without merging**
