### PR TITLE
[meta] Adding `compiler` to `DXVK_HUD`

### PR DESCRIPTION
**Pull request by concatime**
https://github.com/doitsujin/dxvk/commit/7dc449a

### CODE REVIEW

**Comment by doitsujin** [comment]
That's a bit misleading since it does **not** show anything when the shaders are not being compiled from the state cache.

For that reason I'm not sure if it's a great idea to document this at all, it's not a useful HUD indicator and should probably be removed again.

**Comment by concatime** [comment]
It's not that useless, because it's used by some install script from lutris: https://lutris.net/games/install/10154/view (`DXVK_HUD: compiler`).

**Comment by doitsujin** [comment]
Yes, I'm aware of that; that's why it was added in the first place. I still don't want the broader public to think it's doing something that it isn't actually capable of doing.

**Comment by h1z1** [comment]
Just to confirm are you saying when that shows on the HUD it's _only_ for new shaders?   To wit the lack of such output means either no compilation or it's coming from cache?

If that is the case Valve's precaching isn't doing much because I see that all the time.

**Comment by K0bin** [comment]
> Just to confirm are you saying when that shows on the HUD it's only for new shaders? To wit the lack of such output means either no compilation or it's coming from cache?

It's the exact opposite. It's only showing when DXVK compiles shaders it already has encountered in an earlier run. It's impossible to show the message for new shaders.

**Comment by h1z1** [comment]
Interesting.  That still doesn't match up with what I've seen which is most of the time that message conincides with studdering.   Granted it never occurred to me such distinction were present nor to check the code I'm quite curious.  Can't imagine I'd be the only one.

**Comment by Kreyren** [comment]
i think that more options for info in `DXVK_HUD` is always good thing

**Comment by pchome** [comment]
@doitsujin 
I have a question: is it possible to make counters visible outside DXVK?
To use them in e.g. [Conky](https://github.com/brndnmtthws/conky). 

Why? Well, even not 100% accurate it should be useful while playing a game in window, where the counters data would be represented **near** a game window, not inside.
(thinking about sysfs/procfs/debugfs, but not sure it's possible)

**Comment by odysseywestra** [comment]
What about just changing the wording on the HUD to `Compiling Pre-Cached Shaders`? That should help with some of the confusion since it's already know that DXVK uses shader caches. Then that would make sense on the documentation end.

**Pull request merged**
