### PR TITLE
[build] Support custom Wine versions

### PR DESCRIPTION
**Pull request by forkbomb9**
This allows people to use custom wine versions by exporting the WINE env variable.
re. https://github.com/doitsujin/dxvk/issues/2193

If undefined, it uses the `$PATH`'s `wine` using `command -v` instead of `which`.
This is POSIX compliant (also Debian 11 deprecated which)

### CODE REVIEW

**Comment by pchome** [comment]
or just export PATH
also try this PR with `export WINE=wine` or `export WINE=some_random_user_input/idk` or some random formatC command

**Comment by forkbomb9** [comment]
Exporting a new PATH is not always as nice as just pointing `WINE`, scripts et all.
`WINE=wine` it works as expected (it's like reverting to the previous behavior), and a random input it doesn't work (this was already checked at line 75 & 76.

**Comment by doitsujin** [comment]
We already rejected the exact same thing multiple times already. If you for whatever reason have such a non-standard setup that the script doesn't work, don't use the script.

**Comment by forkbomb9** [comment]
Sorry, I hadn't seen this kind of change rejected. I just saw that issue I linked.

**Pull request closed without merging**
