### PR TITLE
[d3d9] Reject Reset if there's any remaining DEFAULT resources

### LINKED ISSUE #3472: [d3d9] THE KING OF FIGHTERS XIII: STEAM EDITION: Missing Graphics
Was testing out this game on my steam deck when I noticed it had some weird graphical quirks going on that were also reported on the proton github page for this game (But didn't seem to be present when using proton 4.11-13) so I figured i'd hop on my windows laptop to test it out on there with DXVK and noticed these issues (Since testing it out on deck requires a command to skip the videos or else it crashes the game and dunno how to setup the commands to skip videos and make a log file)

DXVK:
KOF DXVK 1
KOF DXVK 2

How it should look:
KOF 1
KOF 2

### Software information
THE KING OF FIGHTERS XIII: STEAM EDITION

### System information
- GPU: AMD Van Gogh for Steam Deck, GTX 1650 for the Windows Laptop
- Driver: Mesa 22.2.0 for Steam Deck,   Nvidia 531.79 for Windows Laptop
- Wine version: 8.0 on Steam Deck
- DXVK version:  https://github.com/doitsujin/dxvk/actions/runs/5126995523, also tested on latest dev build available at time (Respect all PS input elements for registers)

### Apitrace file(s)
- https://www.mediafire.com/file/5u08nqdf4yndrik/kofxiii.zip/file
 Mediafire link since it's apparently too big for github.

For instructions on how to use apitrace, see: https://github.com/doitsujin/dxvk/wiki/Using-Apitrace

### Log files
Please attach Proton or Wine logs as a text file:
- When using Proton, set the Steam launch options for your game to `PROTON_LOG=1 %command%` and attach the corresponding `steam-xxxxx.log` file in your home directory.
- When using regular Wine, use `wine game.exe > game.log 2>&1` and attach the resulting `game.log` file.

[kofxiii_d3d9.log](https://github.com/doitsujin/dxvk/files/11641930/kofxiii_d3d9.log)

### PR DESCRIPTION
**Pull request by K0bin**
Fixes #3472

### CODE REVIEW

**Comment by WinterSnowfall** [comment]
... and don't forget to also include a config option for the game. Speaking of which, the existing regex should probably be expanded to include the GOG release, which uses `kof13_win32_Release.exe`.

**Comment by K0bin** [comment]
I'm currently considering doing this by default for every game.

**Comment by K0bin** [comment]
Changed it so it's done by default. I also tested how D3D9Ex handles this.

**Comment by K0bin** [comment]
Okay, I think I got this right now but it'll take a lot of testing.

**Comment by K0bin** [comment]
> Shouldn't all those "Device reset failed" messages have WARN log level?

I guess you could argue that. In practice it's probably gonna be something that happens in some games and is totally benign.

**Comment by WinterSnowfall** [comment]
My 2 cents: rather than getting issue reports from people believing something abnormal is happening, I'd keep it swept under the proverbial rug.

**Pull request merged**
