### PR TITLE
[native] Include all supported wsi backend headers

### PR DESCRIPTION
**Pull request by Blisto91**
So applications actually can support multiple backends with the same .so

### CODE REVIEW

**Comment by pchome** [comment]
1. Are you sure  `#if not defined(DXVK_WSI_SDL3) || DXVK_WSI_SDL2 || DXVK_WSI_GLFW` will work?
  should be `#if !defined(DXVK_WSI_SDL3) && !defined(DXVK_WSI_SDL2) && !defined(DXVK_WSI_GLFW)`
2. Are you sure those headers are not overlap?
  I know almost nothing about SDL, so maybe yes or maybe not (overlap).

**Comment by Blisto91** [comment]
No it was indeed wrong. I drafted it because i had to go away so couldn't fix it immediately

**Comment by Blisto91** [comment]
The second question I'll CC @flibitijibibo for

**Comment by flibitijibibo** [comment]
Can confirm that this would cause conflicts. For native applications that actually plan to support multiple backends, odds are the backends in the application itself would also be split up to avoid the same kind of issues, so each backend can separately include the correct wsi.h without having to worry about collisions.

**Comment by Blisto91** [comment]
Thank you for the input both of you. I'll go ahead and close this.

**Pull request closed without merging**
