### PR TITLE
[build] Add soversion to dxvk-native binaries

### PR DESCRIPTION
**Pull request by flibitijibibo**
Part of #3451

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Quick update to use meson.project_version() to get the major/minor version of the soname, to avoid adding new constants that need bumping for every release.

**Comment by Joshua-Ashton** [comment]
You need to update `package-native.sh` to handle symlinks or something, it's actually extracting like 3 copies of the .so rn.

I am also not completely confident we need soversioning? We should never be breaking ABI.

**Comment by flibitijibibo** [comment]
Will look into the symlinks soon, I don't think the artifact zip files will be able to preserve them so this would only help the tar releases.

@smcv may have a better explanation but I think this is needed in case a breakage is necessary; the unversioned .so should only be present as part of the development package.

**Comment by flibitijibibo** [comment]
Confirmed that artifactsv3 is what's causing the symlinks to get resolved, so the latest push includes a commit to tar the steamrt-sniper build. I could have sworn that the action supports using tar as the format, but even their own README suggests using tar inside of the zip to fix this, so here we are...

**Comment by flibitijibibo** [comment]
Looks like the added `.1` caused some problems with dxvk_so_version - any preferences on how to deal with this? Currently thinking of just making another string at the top that ignores any numbers after the first two, but maybe there's a better way to do this.

**Pull request closed without merging**
