### PR TITLE
[util] Set Secret World Legends launcher to SM 2

### PR DESCRIPTION
**Pull request by Blisto91**
With default shader model 3 the launcher UI elements are invisible.

<details>
  <summary>Screenshots without and with the option</summary>
  
Screenshot_20221126_214912
Screenshot_20221126_214838
</details>

### CODE REVIEW

**Comment by K0bin** [comment]
Do we know what the problem is? If it's partial presentation, I'd be fine with merging this as a workaround. If not, I'd rather investigate the root cause.

**Comment by Blisto91** [comment]
No idea. I asked a couple of times if anyone had any ideas on discord since it doesn't seem like a partial presentation issue, but didn't get any feedback and just opted for the PR for now. Can also make a issue if you think so.
Sadly apitrace has issues replaying traces made for the launcher. Even captured on windows and replayed natively again there. So will  have to make a issue at the apitrace repo also i guess.

**Comment by K0bin** [comment]
Please open an issue.

**Comment by Blisto91** [comment]
https://github.com/doitsujin/dxvk/issues/3116

**Comment by Blisto91** [comment]
Reopenes since Partial Presentation is suspected anyway

**Pull request closed without merging**
