### PR TITLE
[util] Fix e2k build

### PR DESCRIPTION
**Pull request by r-a-sattarov**
Ref: https://en.wikipedia.org/wiki/Elbrus_(computer)

### CODE REVIEW

**Comment by jams3223** [comment]
Why are you adding this CPU architecture? Are we trying to support games under this architecture?

**Comment by r-a-sattarov** [comment]
> Why are you adding this CPU architecture?

This CPU architecture developed in Russia, started at 200X. Now 6th generation of CPU is available. It was rather uncommon but now is going to target mass-market (at least in Russia), when home workstations are built with this CPU.
- https://en.wikipedia.org/wiki/Elbrus_2000

> Are we trying to support games under this architecture?

The [Perimeter](https://github.com/KD-lab-Open-Source/Perimeter)  game uses this library in its graphics rendering for Linux. Therefore, I decided to add support for E2K (maybe more games will appear in the future).

**Review by Toxblh — APPROVED** [review]

**Comment by K0bin** [comment]
Whats the point of this? All D3D9/11 games are x86 or x86_64.

**Review by ysukhovey — APPROVED** [review]

**Comment by Joshua-Ashton** [comment]
Does the Linux Kernel even have support for this architecture? This is unlikely to be very useful unless it is supported there.

**Comment by a1batross** [comment]
@Joshua-Ashton hi Josh!

It has [Linux port](https://git.mentality.rip/OpenE2K/linux), [binutils-gdb](https://git.mentality.rip/OpenE2K/binutils-gdb), LLVM and [many more](https://github.com/ilyakurdyukov/e2k-ports). The ISA documentation is NDA'ed, but there we were able to reverse-engineer some of it and implement [a user-mode emulator](https://git.mentality.rip/OpenE2K/qemu-e2k).

There is an ongoing, unofficial efforts, mostly led by third-party, some unpaid, developers, to upstream the patches. There isn't much so far, and nearly zero if we're talking about the most complex ones.

**Comment by DjArt** [comment]
@Joshua-Ashton also there demo zone: https://elbrus.kurisa.ch/

**Comment by jams3223** [comment]
> > Why are you adding this CPU architecture?
> 
> This CPU architecture developed in Russia, started at 200X. Now 6th generation of CPU is available. It was rather uncommon but now is going to target mass-market (at least in Russia), when home workstations are built with this CPU.
> 
> * https://en.wikipedia.org/wiki/Elbrus_2000
> 
> > Are we trying to support games under this architecture?
> 
> The [Perimeter](https://github.com/KD-lab-Open-Source/Perimeter) game uses this library in its graphics rendering for Linux. Therefore, I decided to add support for E2K (maybe more games will appear in the future).

Can't they just compile an x86 or x86_64 version of the game?

**Comment by r-a-sattarov** [comment]
> Whats the point of this?

The main idea is to add E2K support for games that use this library in their graphic render (such as the game [Perimeter](https://github.com/KD-lab-Open-Source/Perimeter)).

> All D3D9/11 games are x86 or x86_64.

Nevertheless, I see that in the code of DXVK there is support for the [ARM](https://github.com/doitsujin/dxvk/blob/master/src/util/util_bit.h#L8) architecture.

**Comment by r-a-sattarov** [comment]
> Does the Linux Kernel even have support for this architecture?

At the moment, there is no official support for the E2K architecture in the Linux kernel, but MCST is expected to publish its kernel source code this year.

> This is unlikely to be very useful unless it is supported there.

As I wrote above, I want to simplify the development of games that use DXVK in their code (so that they can compile for E2K without major problems).

I think no maintaining is required from your side - maybe just I will occasionally send patches if code stops compiling after some large changes - but I don't expect so.

**Comment by r-a-sattarov** [comment]
> Can't they just compile an x86 or x86_64 version of the game?

The Perimeter game is multi-platform and runs on many architectures (amd64, aarch64, e2k).

**Comment by DileSoft** [comment]
> > Whats the point of this?
> 
> The main idea is to add E2K support for games that use this library in their graphic render (such as the game [Perimeter](https://github.com/KD-lab-Open-Source/Perimeter)).
> 
> > All D3D9/11 games are x86 or x86_64.
> 
> However, I see that there is [ARM](https://github.com/doitsujin/dxvk/blob/master/src/util/util_bit.h#L8) support in the DXVK code.

As maintainer of https://github.com/KD-lab-Open-Source/Perimeter I can confirm that is was runned on E2K.

**Comment by doitsujin** [comment]
Which of these changes are strictly necessary to make DXVK compile at all? I don't really want to do more than the *bare minimum* here especially as long as there's no official upstream kernel support, nor do I want it to look like we officially endorse the architecture.

**Comment by a1batross** [comment]
It already seems to be minimal enough to avoid all the `#error`s.

Though I wouldn't even check for intel intrinsic presence because the needed wrappers do __always__ present in the toolchain. The use of `if( X86 || E2K ) { /* intrinsics */ }` does the job anyway.

**Comment by r-a-sattarov** [comment]
> Which of these changes are strictly necessary to make DXVK compile at all? I don't really want to do more than the _bare minimum_ here especially as long as there's no official upstream kernel support, nor do I want it to look like we officially endorse the architecture.

Done. The bare minimum (compiles and ready for minimal use).

**Pull request merged**
