### PR TITLE
[d3d11] Fix device child refs properly

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
Mainly opening this right now so we can get some testing done and tracking of issues.

Please let me know if you have any problems/issues with this PR in games below!

Thanks.

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Tested this with Okami and Dear Esther Landmark Edition (Unity)

**Comment by Oschowa** [comment]
No issues with Sekiro, Yakuza 2 and 7, Atelier Ryza or Senran Kagura Burst Re:Newal

**Comment by vitorhnn** [comment]
Disco Elysium (Unity 2019.4.9 I think?), Project Wingman (UE4.24), Resident Evil 2, The Witcher 3 and Dark Souls 3 are ok

**Comment by Joshua-Ashton** [comment]
Works in Metro Last Light Redux.

**Comment by ViNi-Arco** [comment]
Good afternoon Joshie, Works well on **Dark Souls: Remastered** on the latest version of the game on Steam..

**Comment by edmondo** [comment]
Works with PoE (DX11) and Stalker Anomaly (DX11).

**Comment by Yjnar** [comment]
Tested with The Surge (DX11). Works as it did previously with DXVK master. Will do more testing with other DX11 games I have installed.

**Comment by flgx16** [comment]
Tested with:
- Metro 2033 Redux
- Grand Theft Auto V
- The Forest
- Tomb Raider

Seems to be working.

**Comment by dustContributor** [comment]
Fallout 4 seems to working. Ran around some FPS tanky urban areas, fast traveled a bit, everything seemed fine.

**Comment by doitsujin** [comment]
Ran FFXIV with this and it was fine for several hours of gameplay.

**Pull request merged**
