### PR TITLE
[RFC][D3D9]Avoid infinite loops in SetCursorPosition 

### LINKED ISSUE #1400: [d3d9] Sins of a Solar Empire - Rebellion hangs on load screen
The game hangs after showing the loading screen. A mouse cursor (which you can move around) shows up at some point, but neither frantically clicking or pressing any keys has any effect. Needless to say, without dxvk the game shows the intro cinematics and takes you to the main menu without issues.

What I tried and had no beneficial effect with dxvk:
- disabling intro videos
- forcing the game to start in windowed mode

Since it's hard to capture all I said in pictures, here are videos of:

[Sins of a Solar Empire starting up with dxvk](https://drive.google.com/open?id=1_c3yphFJVO0Trsfhthl-Y4oHc7HhukRf)
[Sins of a Solar Empire starting up with WineD3D](https://drive.google.com/open?id=1IJK1zJfzHSUdhNet9YbsySbPJUpfhM-4) (I skipped the long intro video to land on the menu)

The second video was recorded in the same Wine prefix, after uninstalling dxvk.

### Software information
Sins of a Solar Empire - Rebellion (GOG version, with the latest official patch + Outlaw Sectors DLC).

### System information
- GPU: GeForce GTX 1070
- Driver: 440.48.2
- Wine version: 5.1 Staging
- DXVK version: v1.5.3+87dd8f01

### Apitrace file(s)
[Sins_of_a_Solar_Empire_Rebellion.trace.tar.xz](https://drive.google.com/open?id=1bW9AFNw_CkWnqrByqbUHgKMSMhhCI5qL)

### Log files
- d3d9.log: [Sins of a Solar Empire Rebellion_d3d9.log](https://github.com/doitsujin/dxvk/files/4161354/Sins.of.a.Solar.Empire.Rebellion_d3d9.log)
- d3d11.log: N/A
- dxgi.log: N/A

### PR DESCRIPTION
**Pull request by Altosk**
based on G9 solution 
Fixes #1400

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
Ah, I think the problem here is the cursor move window message is calling ``device->SetCursorPosition`` and that's triggering forever, right?

I think what instead we should be doing is also tracking win32 setting the cursor here (ie, just use ``GetCursorPos``), not just what we set it to in the API.

Thanks for finding this issue out, I'll do some testing locally and see if I can figure out what native actually does here 😄

**Comment by Altosk** [comment]
No problem at least it's something for now 😁

**Comment by Joshua-Ashton** [comment]
Can you test with my branch?

https://github.com/doitsujin/dxvk/tree/d3d9-cursor-pos

**Comment by Altosk** [comment]
Will do when I get back home

**Comment by Altosk** [comment]
looks good here got to the main menu with no freezing

**Comment by Joshua-Ashton** [comment]
Cool, I shall merge it then. 😄

**Comment by Joshua-Ashton** [comment]
Superseded by https://github.com/doitsujin/dxvk/commit/f688889b413d966b0e1894755ebe7678709671fd

**Comment by WinterSnowfall** [comment]
@Altosk @Joshua-Ashton Thanks a lot to both of you for figuring this out :). Both Sins of a Solar Empire and the Act Of War games I was having issues with work fine now. Well, Sins of a Solar Empire seems to have serious performance issues, but I'll open a separate bug for that. Cheers!

**Pull request closed without merging**
