### PR TITLE
WIP: Native Port

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
This PR allows DXVK to be built natively on Linux with an option to specify the WSI you want to use.

This allows titles to port to Linux and potentially other platforms further down the line much easier by letting them keep their existing rendering code for D3D11.

The exact same code path can also be used on Windows if the title wishes to ship with DXVK there too, and is compatible with the regular Windows headers (ie. you can use SDL2 WSI intergration on Windows builds as well.)

### CODE REVIEW

**Comment by Joshua-Ashton** [comment]
[Turns out Github drafts are not the same as Gitlab ones :frog:]

**Comment by doitsujin** [comment]
I'm going to leave this open for now until a final decision is made, but as discussed on Discord, with DXVK entering maintenance mode, I'd like to avoid any significant changes or additions to the code base that are not strictly necessary.

**Comment by eszlari** [comment]
>  with DXVK entering maintenance mode

Is this, because you consider DXVK to be feature complete?

**Comment by doitsujin** [comment]
> Is this, because you consider DXVK to be feature complete?

It's because DXVK has become a fragile, unreliable and frustrating maintenance nightmare. Most of the 1.4.x releases introduced major regressions which I cannot reproduce, and therefore cannot debug and fix.

This includes GPU hangs in Overwatch on specific maps (some users claim it's fixed in 1.4.6 while others still have them), rendering issues in Dishonored 2 which I can't reproduce (see https://github.com/ValveSoftware/Proton/issues/823#issuecomment-563254620), vertex explosions in some games which I also can't reproduce, an ongoing Star Citizen issue which I still need to debug (see #1262), and tons of weird issues that don't make any sense whatsoever (like #1266 which only seems to affect RADV).

All of these problems are still unresolved and I have no idea how to even track them down, let alone fix them. Doing any sort of active development with this broken mess of a code base has become impossible, and it's best to put it to a rest. The only thing I still plan to do is wire up some useful Vulkan extensions and eventually merge D9VK, the rest will be bug fixing.

**Comment by jediafr** [comment]
It does sound like a burnout. I would advise 2 weeks iatus to stop working in crunch mode. A rethinking of the framework might benefit the project long term. Valve can understands this.

**Comment by Pyrathar** [comment]
It does sound like burnout, but sir i would like to say that im pretty sure everybody in gaming linux community is thankful for your work, this made such a huge impact in my life and im sure it did on a lot of other people aswell, take a vacation mate! you more than earned it!

**Comment by veryprofessionaldodo** [comment]
I agree with what was stated above, you did some amazing work, and I'm incredibly thankful for your achievements! @doitsujin

**Comment by devland** [comment]
Hey, Philip. We really appreciate your work. It's been inspiring to watch this project evolve over time and to see real world applications at a small (me playing Windows games in lutris) and large scale (Valve's Proton).

I'm a developer myself and what you're experiencing sounds a lot like you need a vacation. Working on the same piece of code for long periods of time will get you tunnel vision and the only way out is to just take a break and relax. :)

**Comment by RealXor** [comment]
Hey Phil, same here, I can probably speak for the community for this matter, take a break. Do it for yourself, and instead just focus on your personal live man, you need to catch up!

Have a nice day bro!

**Comment by PMunkes** [comment]
Just wanted to say thank you for all your hard work. Take a few weeks off, at least till the new year.

**Comment by wdbm** [comment]
DXVK is awesome. I simply will not use malware like Windows, so DXVK means I can enjoy the likes of *Alien: Isolation* or Gwent. Thank you. :)

**Comment by brenthuisman** [comment]
Hang in there @doitsujin, you've been doing the unimaginable with unimaginable success. Take care of yourself and take your time!

**Comment by julienbenjamin** [comment]
> > Is this, because you consider DXVK to be feature complete?
> 
> It's because DXVK has become a fragile, unreliable and frustrating maintenance nightmare. Most of the 1.4.x releases introduced major regressions which I cannot reproduce, and therefore cannot debug and fix.
> 
> This includes GPU hangs in Overwatch on specific maps with Nvidia GPUs (some users claim it's fixed in 1.4.6 while others still have them), rendering issues in Dishonored 2 which I can't reproduce (see [ValveSoftware/Proton#823 (comment)](https://github.com/ValveSoftware/Proton/issues/823#issuecomment-563254620)), vertex explosions in some games which I also can't reproduce, an ongoing Star Citizen issue which I still need to debug (see #1262), and tons of weird issues that don't make any sense whatsoever (like #1266 which only seems to affect RADV).
> 
> Most of these problems are still unresolved and I have no idea how to even track them down, let alone fix them, and the ones that got "fixed" got fixed by reverting otherwise useful changes because I simply do not understand any of the issues at all.
> 
> Doing any sort of active development with this broken mess of a code base would only make this worse, and I wish I had drawn the line sooner. The only thing I still plan to do is wire up some useful Vulkan extensions and eventually merge D9VK, the rest will be bug fixing only.

Is there any way to help you out, without knowing how DXVK has been designed?

**Comment by Fordi** [comment]
I don't know about the current structure, but in my experience, compatibility layers tend to start as a straightforward API surface, which descends into a mess of heuristics and hacks as edge cases are found and addressed, until a breaking point where Things Must Change.  It sounds like you're nearing that crest (which sucks).

If you had all the time in the world, and didn't have to worry about risk, is there a way you would restructure DXVK to be easier to maintain?  If you can define it readily, it might be that you can petition Valve to get you more resources for a re-arch to simplify maintenance without having to promise performance improvements for a while.  Get them to commit to a bug moratorium and give you people to help you clean house.

But like others said, you should maybe take some vacation for the holiday season, do something nice for yourself.  Graphics drivers and compatibility layers and other things users _shouldn't_ notice are thankless, grueling work, rife with heisenbugs and opaque stacks - but you still manage to fix some crazy shit.

Let yourself have a real reward, and I think I speak for the whole community when I say you seriously deserve it.

**Comment by telmotrooper** [comment]
@doitsujin I just can't thank you enough for how much of a difference you've made in the status quo of computer gaming. Wish you best of luck!

**Comment by Joshua-Ashton** [comment]
Come play TF2 with me and @liam-middlebrook 🐸

**Comment by doitsujin** [comment]
> If you had all the time in the world, and didn't have to worry about risk, is there a way you would restructure DXVK to be easier to maintain?

My main issue is that I simply don't understand most of the issues that are popping up everywhere, not that the code base itself is poorly structured. There are some things that could use some cleanups, but the last attempts at doing that have caused exactly the kind of regressions I was complaining about, and it really seems like touching *anything* causes some arbitrary breakage for no particular reason.

**Comment by Fordi** [comment]
If opacity is the problem, would the next big step be instrumentation?

**Comment by doitsujin** [comment]
No since that would either cause a major performance hit or make everything incredibly messy (or both).

**Comment by Fordi** [comment]
Could try something that encapsulates basic patterns to avoid ifdef cruft, like:

```
#ifdef TRACING
#define INSTRUMENT(stmt) beginInstrument();\
 stmt \
endInstrument();
#else
#define INSTRUMENT(stmt) stmt
#endif
```

**Comment by doitsujin** [comment]
I mean it's not like it couldn't be done, usually I do that manually when tracking down a crash or bug for the functions where it matters, but there are multiple issues with that approach.
- We can't debug GPU hangs this way, at all. This needs GPU-side work, and obviously extra code on the CPU side to actually do that.
- Even if purely CPU-side debugging is useful (e.g. when something segfaults), demanding games easily do >10 million API calls per second. Logging all of those, plus all the backend work, would be insane.
- There's just so much going on on multiple threads that just spamming messages everywhere won't necessarily make it easier to figure out what the actual problem was. Wine's debug channels kind of have the same problem; if things don't work due to an unimplemented feature it's easy to figure out; if the problem sits deeper than that, it often isn't.

**Comment by barotto** [comment]
The fact that many PC gamers like to overclock their systems is not helping either. I think one requirement for bug reporting should be "please, if your system is overclocked in any way (CPU, GPU, and/or RAM) retest at stock before reporting bugs."

**Comment by brianinthered** [comment]
I also thank you Phillip for all of your dedication and hard work!
I test windows games in Wine on a daily basis and post step-by-step guides in PlayOnLinux weekly.  Without DXVK most of my tests will fail because of DirectX 10/11
Thanks to you we have so many games and guides that allow us to play indie "windows only" games from itch.io and AAA games from GOG!

Definitely take a break and clear your head and give it a second pair of eyes later on.  Refresh yourself and enjoy some time off.  It won't affect us at all... we can wait!  I've waited years to see Windows DirectX 10/11 games to run in Linux so I have no problem waiting a few weeks or even months!

By the way, what bugs have you noticed?  Almost every Unity3D and Unreal Engine game I've tested runs great with every version of DXVK I test.  I rarely notice any issues at all.

**Comment by dhollinger** [comment]
@doitsujin Is there any situation where you'd feel comfortable handing the project maintainership off to another person or a community to maintain?

**Comment by o-bri** [comment]
Hi Philip,

thanks for your work so far!

I think it would be important, that you don not do all this work alone. It is amazing, that you came this far with this complex piece of work.

Perhaps you can take a break an Valve should organize, that you have 1-3 devs to help you and discuss problems an solutions with them.

I hope this is not the end of the amazing duo DXVK/Proton.

Kind regards
Oliver

**Comment by gardotd426** [comment]
> DXVK is awesome. I simply will not use malware like Windows, so DXVK means I can enjoy the likes of _Alien: Isolation_ or Gwent. Thank you. :)

Alien: Isolation has a native version though?

Anyway, @doitsujin I just want to pile on with what everyone else said. Your project here has made a gigantic impact on my life, and I hope that isn't lost on you. A lot of us REALLY love games, but the thought of having to even dual boot and use Windows to play them makes us legitimately upset/sick. Sure, there are some huge games I'd love to play but can't because I won't make that sacrifice of using Windows at all, but because of you, and Valve, and @GloriousEggroll, and the people at @Lutris, I can play MORE than enough amazing games. Without you, I honestly would have had to swallow my disgust and use Windows, but because of you, I get to keep thoroughly enjoying my computer while also retaining control of it and use the operating system I truly love. 

You're honestly one of the Mount Rushmore faces of Linux Gaming along with GE and @TK-Glitch, and even if you never develop DXVK again, you've done more than enough. Take a break.

**Comment by mphuZ** [comment]
**_doitsujin_**, I hope you will put your efforts into the VKD3D project.

**Comment by brunonymous** [comment]
Hello Philip, 

I would like to thank you for all the work you have done on DXVK.  Thanks to your work my son can play a lot of Windows games under Ubuntu Linux 18.04 (Overwatch, Monster Hunter: World, ...).

Thank you again and don't give up.

Best regards
Bruno

**Comment by shadywack** [comment]
Just to add to the chorus, I hope you can try not to be too hard on yourself Philip. 

DX11 itself was something developed by teams of people with various committees involved. DXVK stands on the shoulders of giants as well as Vulkan itself is far from simple. This work has benefited me in ways difficult to quantify, liberating, freedom, choice? I really hope you take a step back, breathe, and decide how to go from there. Whether or not DXVK goes into a maintenance mode, gets new features, gets new speed or whatever, I appreciate you and everyone who has worked on it. I sincerely appreciate the time everyone has taken to get it this far. 

Spend holidays with family, take care of yourself, we love you.

**Comment by NodokaHanamura** [comment]
I Logged into this barely used github account just to say thank you for your hard work on DXVK. If I had any knowledge of programming pertaining to DirectX, Vulkan or anything that DXVK would rely on I'd gladly try and help out, but sadly I'm still a newbie when it comes to programming.

Thanks to DXVK, Linux finally has become a proper alternative to Windows that I can use as a daily driver outside of VR (But that's no fault of your own, VR is still a niche tech that is still growing).

Don't beat yourself up too hard on having an issue with it - take a step back and enjoy the holidays and come back with a clear mind. That's what I often do when I can't figure out something.

All in all, I wish you the best of luck with fixing this.

**Comment by procedural** [comment]
> * Even if purely CPU-side debugging is useful (e.g. when something segfaults), demanding games easily do >10 million API calls per second. Logging all of those, plus all the backend work, would be insane.

You're dealing with games with bugs and erroneous assumptions that had secret workarounds in D3D11 drivers on Windows that must run through not perfect Windows emulation layer using buggy graphics drivers on Linux, how insane you think this problem is?

1. Make it easy for users to run and report with vktrace or whatever the new version LunarG people cook right now is called.
2. Ask Valve to buy all the graphics cards users have, build a test lab.

**Comment by ValZapod** [comment]
@doitsujin I think in many cases Nvidia should be blamed for this)) It is not that you do not understand the code it is that they always broke it in their driver. Simple. For example this issue https://github.com/doitsujin/dxvk/issues/956: we have it on windows too. Surprise. https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/333239/devil-may-cry-vresident-evil-2-biohazard-re2-brig/2341397/

I also think I will check you code with my analyser, some simple fixes could be a nice change))

**Comment by procedural** [comment]
> vktrace or whatever the new version LunarG people cook right now is called.

https://www.lunarg.com/lunarg-releases-new-sdks-for-vulkan-header-1-1-130-0/

> The vktrace and vkreplay tools currently included in this SDK will be removed in the next 3-6 months. It will be replaced with GFX Reconstruct. Vktrace/vkreplay will still be available via a github repository but will not be included in future SDKs.

**Comment by justeff** [comment]
If Nvidia is the problem, we shouldn't give a shit about them. Seriously, if their drivers are a broken mess, you shouldn't adapt the code for workarounds.

Regarding GPU tracing, is there some work ongoing by AMD or Nvidia?

Besides that, thanks to DXVK Windows is gone forever (except at work lol). No dual-boot anymore, I would say 50% of my games work out of the box now.

**Comment by K0bin** [comment]
Nvidia isn't the problem. Their drivers work fine and dropping support for at least 65% of users isn't an option.

**Comment by Diliz** [comment]
Hello!

Thanks for all the work, I wanted to post a big hug message to the community here, but most of the ppls would have read it xD

So this is just a big thanks, much love and stay cool ppls, sometime take a break is the best way to handle things.

PS: If you don't know what's the problem with some buggy stuff, I recommend trying to list the broken stuff, and make a study with your mates, let some mates try to identify what's broken, more brains, more possibilities :)

**Comment by Arxcis** [comment]
Hey @Joshua-Ashton. I want to start contributing to `dxvk` and this PR here spurred my interest in partical. What a great initiative. Native DXVK ftw! :D 

Is there anything I can do to help move this PR forward? Maybe I can do some testing? Compile on my system? Code review? Fix conflicts? Anything else?

**Comment by Joshua-Ashton** [comment]
Hi @Arxcis, I actually moved development to the dxvk-native repo on my profile. That's rebased against something fairly close to master now. I'm going to hook up thread priority stuff shortly and add an option to compile statically.

**Comment by Arxcis** [comment]
Cool. That kind of makes sense for such a big change like this. Do you see it as a separate project, or do you eventually want to merge it back into `dxvk` ? I can imagine it must be hard keeping the two projects compatible with each other.

**Comment by bruhhhxyt** [comment]
Wow

**Pull request closed without merging**
