### PR TITLE
[tests] Get DXBC tests building natively.

### PR DESCRIPTION
**Pull request by Joshua-Ashton**
We can use what was built on here for shader compilation for D3D11/D3D9 tests.

### CODE REVIEW

**Comment by doitsujin** [comment]
Is there any particular reason why we need this?

This just seems like a *huge* fucking mess for no real benefit, the dxbc and hlsl compiler stuff is mostly used for debugging purposes anyway and requires a properly functioning d3dcompiler implementation anyway.

**Comment by Joshua-Ashton** [comment]
@doitsujin We still need to build the regular samples, and they all compile shaders and will use the same thing here. I just picked `dxbc` as a starting point because it was easy to get going

**Comment by doitsujin** [comment]
I'd rather do a more radical thing and remove all the samples, except like one super basic triangle app that supports all three APIs or something. Would need to be written.

The tests we have right now aren't great anyway, and I'd rather move the more useful ones to a separate repo and drop the ones that no one uses anymore (things like d3d11-streamout and a whole bunch of d3d9 stuff).

**Comment by doitsujin** [comment]
Solved by moving tests to https://github.com/doitsujin/dxvk-tests.

**Pull request closed without merging**
