### PR TITLE
[util] Enable strict float emulation for NFS Carbon

### PR DESCRIPTION
**Pull request by TheComputerGuy96**
This fixes a random segfault with NVIDIA drivers (not sure if NVK is affected though because I didn't test it with NVK yet 😄)

I've been meaning to push this for a while but I didn't do it until now 🐸

### CODE REVIEW

**Comment by doitsujin** [comment]
If we segfault then we should figure out *why* we're segfaulting rather than just put a band-aid on it that doesn't actually fix the root cause.

Do you have a trace?

**Comment by TheComputerGuy96** [comment]
> Do you have a trace?
I should really make one once I get out of nouveau driver 🐸

**Comment by Joshua-Ashton** [comment]
Are you sure it's a segfault and not a fp exception? Did you actually see it was SIGSEGV?

**Comment by TheComputerGuy96** [comment]
Let's double-check if I didn't mis-remember that it was segfault once I leave nouveau

**Comment by K0bin** [comment]
Nvidia is looking into the compiler crash. So hopefully we won't need this workaround.

**Pull request closed without merging**
